### ISSUE TITLE
remove helmwave.yml.tpl

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#149]
support only helmwave.yml
render from helmwave.yml

**Comment by zhilyaev** [comment]
#159 if we gonna change to gomplate. Take this task too.

**Comment by mumoshu** [comment]
@zhilyaev Hi, a long-time Helmfile maintainer here! I'm looking forward to this project becoming a great alternative to Helmfile.

Will `helmwave.yml` still be rendered with Go template after this change? Then I think that can be a big technical debt like it has been in Helmfile.

You might have several things to consider here.

- Having `.yml` for Go template files makes it hard for an IDE to detect the correct syntax highlighter
- Harder to declare any helm chart values file key whose value is a go template expression that shouldn't be rendered by helmwave (e.g. you're writing [some Prometheus config](https://prometheus.io/docs/prometheus/latest/configuration/template_examples/) for the prometheus chart
- It's hard to build a big go template. There's no breakpoint, debugger, or any unit testing mechanism. No builtin ability to import existing templates for reuse, etc. The consequence is that you are forced to provide free user support for writing Go template like a pro. You might feel like you get a lot of obvious questions from whom who doesn't understand Go template, rather than helmwave itself.

**Comment by zhilyaev** [comment]
@mumoshu welcome! I am glad to see you!

At the moment, we have not made a decision that would suit us. 

This issue is just a point of view.
